apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appname }}
  namespace: pubgrade 
spec:
  ports:
    - port: {{ .Values.containerport }}
      protocol: TCP
      targetPort: {{ .Values.containerport }}
  selector:
    app: {{ .Values.appname }}
  type: ClusterIP
